### ISSUE TITLE
Enhancement: Include converted themes from kitty-themes

### ISSUE THREAD

**Issue by tummyslyunopened** [alacritty/alacritty-theme#113]
Recently converted to alacritty from kitty due to need for better support on windows: 

[kitty-themes](https://github.com/dexpota/kitty-themes) has a lot of useful themee, which can be converted using tools such as [convert-themes](https://github.com/tummyslyunopened/convert-themes) which I used for my own personal config.

For list of themes converted [new-alacritty-themes](https://github.com/tummyslyunopened/convert-themes/tree/main/alacritty-themes)
Would there be any barriers to adding these additional themes to this repo for greater ditribution?

**Comment by chrisduerr** [comment]
>  Would there be any barriers to adding these additional themes to this repo for greater ditribution?

There are plenty of themes in this repository already. Adding a bunch of random themes from other theme collections would likely just bloat the repository while staying completely unused.

If there's individual themes that bring something new to the table that aren't present in this repository yet, feel free to add them on a case-by-case basis.
