### ISSUE TITLE
Non uniform theme file names

### ISSUE THREAD

**Issue by Rizen54** [alacritty/alacritty-theme#119]
The file names are non uniform, some use underscores for spaces while some use hyphens. It leads to ricers being more prone to doing bugs by using wrong symbols, and is kind of frustrating.
If you assign this issue to me, i will rename files to use only underscores as spaces and i'll make sure that i rename every file in a separate commit.

**Comment by Rizen54** [comment]
I'll also edit the readme to replace the old filenames with new ones (which i create).

**Comment by chrisduerr** [comment]
I wouldn't mind a PR to unify the usage of dash and underscore. I don't care *that* much but it wouldn't hurt.

**Comment by chrisduerr** [comment]
> i'll make sure that i rename every file in a separate commit.

This is likely more harmful that beneficial tbh. If you want to put up a PR, that's not necessary.
