### ISSUE TITLE
The theme is not applying on Windows

### ISSUE THREAD

**Issue by SureshPradhana** [alacritty/alacritty-theme#25]
I was trying to apply a theme in Windows, but the theme is not applying. I don't know what the issue is.

### themes import

`cd AppData\Roaming\alacritty\themes\`
`git clone https://github.com/alacritty/alacritty-theme  .`

### folder structure

```
AppData
   └─── Roaming
             └─── alacritty
                       └───themes
                               ├───images
                               └───themes
                                         └───{themes}.yaml

```

### alacritty.yml 

```
import:
  - /AppData/Roaming/alacritty/themes/themes/atom_one_light.yaml
 
 ```

**Comment by SureshPradhana** [comment]
The steps written in this blog (https://www.funkyspacemonkey.com/how-to-easily-apply-and-change-alacritty-themes) worked for me when I installed Alacritty from `npm`

**Comment by chrisduerr** [comment]
Can you share the `alacritty -v` output please? That should show you where configuration files are imported from.

**Comment by chrisduerr** [comment]
Also if you just clone it like that, the directory name will be `alacritty-theme`. So the path would be `/AppData/Roaming/alacritty/themes/alacritty-theme/themes/atom_one_light.yaml` obviously.

**Comment by SureshPradhana** [comment]
`alacritty-v` output
```
PS C:\Users\Suresh>  ] [alacritty] Welcome to Alacritty
[0.000784200s] [INFO ] [alacritty] Version 0.12.1 (5fdfd47f)
[0.005291800s] [INFO ] [alacritty_config_derive] Config import not found:
                                                   "/AppData/Roaming/alacritty/themes/alacritty-theme/themes/atom_one_light.yaml"
[0.005748300s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\Suresh\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.021897600s] [INFO ] [alacritty] Window scale factor: 1
[0.324404600s] [INFO ] [alacritty] Using WGL
[0.367556000s] [INFO ] [alacritty] Running on AMD Radeon(TM) Graphics
[0.368781900s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.427466400s] [INFO ] [alacritty] Cell size: 8 x 17
[0.427837100s] [INFO ] [alacritty] Padding: 0 x 0
[0.428028400s] [INFO ] [alacritty] Width: 800, Height: 600
[0.462358100s] [INFO ] [alacritty] PTY dimensions: 35 x 100
[0.489087000s] [INFO ] [alacritty] Initialisation complete
```

Previously, I attempted by moving the directory. Now, I tried again by cloning using the path '/AppData/Roaming/alacritty/themes/alacritty-theme/themes/atom_one_light.yaml'. I made the necessary configurations in the 'alacritty.yml' file. However, the theme was not applied.

**Comment by SureshPradhana** [comment]
I managed to solve it by replacing the forward slashes ('/') in the path with backslashes ('\') and giving the absolute path
```
import:
  - C:\Users\Suresh\AppData\Roaming\alacritty\themes\alacritty-theme\themes\atom_one_light.yaml
```
After making this modification, the import statement worked perfectly fine.

**Comment by zetolhousa** [comment]
For me this worked:
```toml
import = [
    "C:\\Users\\<your_username>\\AppData\\Roaming\\alacritty\\themes\\<your_theme>.toml"
]
```
