### ISSUE TITLE
Which is the default theme?

### ISSUE THREAD

**Issue by HCY-ASLEEP** [alacritty/alacritty-theme#31]
I really like the default color scheme of Alacritty and would like to port it to other software. Which one is the default color scheme in the README?

**Comment by chrisduerr** [comment]
Currently the default scheme is tomorrow night. The specific values for each color are all documented in Alacritty's manpage:
https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd?plain=1#L224
