### ISSUE TITLE
Will this alacritty theme repo migrate to toml?

### ISSUE THREAD

**Issue by denppa** [alacritty/alacritty-theme#33]
I am trying out the 0.13 dev version, and toml config format looks promising. Will this repo also be updated to use the toml format?

And as a side question, is it possible to programmatically convert the yaml files here into toml files?

**Comment by chrisduerr** [comment]
> I am trying out the 0.13 dev version, and toml config format looks promising. Will this repo also be updated to use the toml format?

Yes, once a stable toml release is made.

> And as a side question, is it possible to programmatically convert the yaml files here into toml files?

`alacritty migrate`
