### ISSUE TITLE
Include Flexoki

### ISSUE THREAD

**Issue by nlubock** [alacritty/alacritty-theme#48]
Could be nice to include this as well!

https://github.com/kepano/flexoki/tree/main/alacritty

**Comment by chrisduerr** [comment]
Not adding themes based on GitHub issue requests. If there's enough interest in a theme, putting up a PR should not be an issue.

**Comment by nlubock** [comment]
Totally fair! I didn't know if there was any complexity in sync'ing between the two repos. I've got a PR here :) #49
