### ISSUE TITLE
How to use a theme after cloning repo?

### ISSUE THREAD

**Issue by davidmickelsen** [alacritty/alacritty-theme#53]
I've successfully cloned the `alacritty-theme` repository:

```
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
```

However, I'm not clear on the next step, to choose a theme and install it for Alacritty. Is there a command I need to run? Do I need to edit my `alacritty.yml` file directly?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty-theme#installation
