### ISSUE TITLE
`zsh: permission denied` when trying to import theme to `alacritty.yml`

### ISSUE THREAD

**Issue by davidmickelsen** [alacritty/alacritty-theme#54]
I've successfully cloned the alacritty-theme repository:

```
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
```

However, when I run

`- ~/.config/alacritty/themes/themes/marine_dark.yaml`

to import the **_marine_dark_** theme to my `alacritty.yml`, I get the error message:

`zsh: permission denied: /Users/davidmickelsen/.config/alacritty/themes/themes/marine_dark.yaml`

**Comment by chrisduerr** [comment]
Please actually read the documentation instead of blindly copy-pasting things into the terminal.

These are not shell commands.

**Comment by davidmickelsen** [comment]
I read the documentation, which is why I ran the command that I did. This is what I understood to do. When it didn't work, I searched the internet for a solution, but did not find an answer. I asked a friend who is more experienced with the command line than I am, but he was also unclear on what I needed to do based on this documentation. That's why I opened the issue; that's why I asked the question. Maybe, instead of accusing people of not reading the documentation, you should consider that your documentation might be a little unclear; or at the very least, that someone relatively new to the command line might have some questions about how to implement the instructions in the documentation, and reply in a civil manner and actually answer the question.

What kind of commands are these, if not shell commands? How do I implement the commands?

Thank you very much.

**Comment by chrisduerr** [comment]
If your reading comprehension is so poor then I recommend using a different terminal emulator (ideally none at all).

**Comment by davidmickelsen** [comment]
I'm sorry you have to live with yourself.
