### ISSUE TITLE
NightOwl theme is missing

### ISSUE THREAD

**Issue by lethjakman** [alacritty/alacritty-theme#72]
According to the [alacritty-night-owl-colors](https://github.com/calimaborges/alacritty-night-owl-colors?tab=readme-ov-file) repo the night owl theme has been moved into alacritty. It seems alacritty's themes have been migrated here, however this particular theme seems to be missing. Is this intentional or was the theme accidentally lost?

**Comment by chrisduerr** [comment]
No theme was intentionally removed, so I can only assume it was never added.

If you want this theme included, feel free to add it again.
