### ISSUE TITLE
Poor contrast of light text against colored background

### ISSUE THREAD

**Issue by itsfarseen** [alacritty/alacritty-theme#76]
Feedback:

1. The colors should be chosen in such a way that it should have sufficient contrast when used as background color with black/white text.
2. Colored background should have uniform brightness.

This blog post is a nice read:
https://blog.ce9e.org/posts/2019-06-24-terminal-colors/

A lot of apps use colored background with light text:

gitui
![image](https://github.com/alacritty/alacritty-theme/assets/40014472/fa857a43-0de0-4417-a6ee-dac2892db029)

Here's an example from this repo itself. 
![image](https://github.com/alacritty/alacritty-theme/assets/40014472/6cdbe79b-b702-49c4-a068-d628b10c0370)

---

Purpose of this issue: 

To raise awareness of key principles in choosing terminal colors.
To raise awareness that these are two desirable property in terminal colorschemes.

I'm not asking the maintainers of this repo to rewrite all the colorschemes here. 

I just want this information to be visible so that some of us may build colorschemes with these properties in the future.

Thanks for the work you're doing for us.

**Comment by kchibisov** [comment]
This repository just collects existing colorschemes formatted for alacritty config format. We don't develop anything here ourselves.

If you have issues with contrast in particular colorscheme complain to the authors of the colorshemes. We don't tweak anything existing.
