### ISSUE TITLE
Warning "Unused config key: import" when trying to import a theme

### ISSUE THREAD

**Issue by LaurensDSchunk** [alacritty/alacritty-theme#77]
## Issue
The catppuccin-mocha theme is not being applied to Alacritty. It is at my ~/.config/alacritty/themes/catppuccin-mocha.toml. When I put in the import statement, I get the warning `Unused config key: import`

## My alacritty.toml
```
# Font configuration
[font.normal]
family = "DejaVuSansM Nerd Font Propo"

# Import additional settings from another file
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]
```

**Comment by chrisduerr** [comment]
Put import at the top of the file.

**Comment by LaurensDSchunk** [comment]
Thank you so much! I'm new to Alacritty and TOML as a whole, so I would have never tried that.
