### ISSUE TITLE
Question about ls colors

### ISSUE THREAD

**Issue by Denisgsv** [alacritty/alacritty-theme#85]
So i tried i think almost all of them and for me 95% have the ls color- folders unreadable.

Basically the one im using gotham is the only one which makes it readable :

https://imgur.com/a/RB9nXLe

for example gruvbox is pretty bad unreadable:

https://imgur.com/a/4offcx2

and catpuccin too:

https://imgur.com/a/yF5qGh2

Or is it something on my side ?

**Comment by chrisduerr** [comment]
You're free to select whichever colors you like for ls. See `LS_COLORS`.
